name: build_werkkzeug3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #- name: Get Short SHA of Commit
      #  run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      #- name: Echo Short SHA to Log
      #  run: echo ${{ steps.sha.outputs.sha_short }}
        
      - name: Get Current Date
        run: CURRENT_DATE=$(date +%Y-%m-%d-%H-%M)
        run: echo $CURRENT_DATE
        
      #- name: Echo Current Date To Log
      #  run: echo ${{ env.CURRENT_DATE }}

      - name: Upload to GitHub Actions Artifact Storage
        uses: actions/upload-artifact@v3
        with:
          name: $CURRENT_DATE-name
          path: /*.*
          if-no-files-found: warn
